# Generated by Django 4.2.23 on 2025-07-24 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'contractors',
            },
        ),
        migrations.CreateModel(
            name='Timelog',
            fields=[
                ('id', models.CharField(db_index=True, help_text='Business ID (same across versions)', max_length=255)),
                ('version', models.PositiveIntegerField(help_text='Version number')),
                ('uid', models.CharField(help_text='Unique ID for this version', max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in milliseconds')),
                ('time_start', models.BigIntegerField(help_text='Start timestamp (milliseconds)')),
                ('time_end', models.BigIntegerField(help_text='End timestamp (milliseconds)')),
                ('type', models.CharField(choices=[('captured', 'Captured'), ('adjusted', 'Adjusted'), ('manual', 'Manual')], default='captured', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('job_uid', models.CharField(db_index=True, help_text='References specific Job version', max_length=255)),
            ],
            options={
                'db_table': 'scd_timelogs',
                'indexes': [models.Index(fields=['job_uid'], name='scd_timelog_job_uid_79071a_idx'), models.Index(fields=['type'], name='scd_timelog_type_941a48_idx'), models.Index(fields=['time_start'], name='scd_timelog_time_st_ed1f49_idx'), models.Index(fields=['time_end'], name='scd_timelog_time_en_e34cdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentLineItem',
            fields=[
                ('id', models.CharField(db_index=True, help_text='Business ID (same across versions)', max_length=255)),
                ('version', models.PositiveIntegerField(help_text='Version number')),
                ('uid', models.CharField(help_text='Unique ID for this version', max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('not-paid', 'Not Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='not-paid', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('job_uid', models.CharField(db_index=True, help_text='References specific Job version', max_length=255)),
                ('timelog_uid', models.CharField(db_index=True, help_text='References specific Timelog version', max_length=255)),
            ],
            options={
                'db_table': 'scd_payment_line_items',
                'indexes': [models.Index(fields=['job_uid'], name='scd_payment_job_uid_cbed58_idx'), models.Index(fields=['timelog_uid'], name='scd_payment_timelog_ca1e33_idx'), models.Index(fields=['status'], name='scd_payment_status_80d16e_idx'), models.Index(fields=['payment_date'], name='scd_payment_payment_9fad2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(db_index=True, help_text='Business ID (same across versions)', max_length=255)),
                ('version', models.PositiveIntegerField(help_text='Version number')),
                ('uid', models.CharField(help_text='Unique ID for this version', max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('extended', 'Extended'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Hourly rate', max_digits=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('contractor_id', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'scd_jobs',
                'indexes': [models.Index(fields=['company_id'], name='scd_jobs_company_d2794c_idx'), models.Index(fields=['contractor_id'], name='scd_jobs_contrac_940037_idx'), models.Index(fields=['status'], name='scd_jobs_status_4c3fa1_idx')],
            },
        ),
    ]
